function [fitresult, gof] = fitGaussianToRgb(L, spd)
%FITGAUSSIANTORGB(L,SPD)
%  Create a fit.
%
%  Data for 'RGB' fit:
%      X Input : L
%      Y Output: spd
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 30-May-2016 18:22:14


%% Fit: 'RGB'.
[xData, yData] = prepareCurveData( L, spd );

% Set up fittype and options.
ft = fittype( 'gauss6' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Lower = [0 425 0 0 425 0 0 500 0 0 500 0 0 615 0 0 615 0];
opts.MaxFunEvals = 6000;
opts.MaxIter = 4000;
opts.StartPoint = [0.963450119467247 455 6.14007145084469 0.635963278722893 445 8.22486557742665 0.606775330604906 510 6.32808946645491 0.514776218304215 465 9.04946199158771 0.433127111468676 520 7.99840074669338 0.329077932612601 500 10.8311552587206];
opts.Upper = [1 475 Inf 1 475 Inf 1 530 Inf 1 530 Inf 1 645 Inf 1 645 Inf];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'RGB' );
h = plot( fitresult, xData, yData );
legend( h, 'spd vs. L', 'RGB', 'Location', 'NorthEast' );
% Label axes
xlabel L
ylabel spd
grid on


